# Generated by Django 3.0.6 on 2020-07-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Deliveried', 'Deliveried'), ('Cancelled', 'Cancelled')], default='Ordered', max_length=10),
        ),
    ]
