# Generated by Django 3.0.6 on 2020-07-13 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200712_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='original_price',
        ),
    ]
