# Generated by Django 3.0.6 on 2020-07-13 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200713_0607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_veg',
        ),
    ]
